# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "williamyeh/ubuntu-trusty64-docker"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # First run - build the docker image
  config.vm.provision "shell", inline: <<-SHELL
    cd /vagrant
    ./docker-build.sh
  SHELL

  # On Startup - start docker container
  config.vm.provision "shell", run: "always", privileged: "false", inline: <<-SHELL
    cd /vagrant
    ./docker-run.sh
  SHELL
end
