# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "williamyeh/ubuntu-trusty64-docker"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 8080, host: 8081, host_ip: "127.0.0.1"

  # Use host dockercfg credentials.
  config.vm.provision :file, source: '~/.dockercfg', destination: '/home/vagrant/.dockercfg'

  # On Startup - start docker containers
  config.vm.provision "shell", run: "always", privileged: "false", inline: <<-SHELL
    docker-compose --file /vagrant/docker-compose.yml up -d
  SHELL
end
