# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "williamyeh/ubuntu-trusty64-docker"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # On Startup - start docker container
  config.vm.provision "shell", run: "always", privileged: "false", inline: <<-SHELL
    docker run -d -p 80:80 -v /vagrant/files:/var/www/html/files markhuber/vagrant-catalog
  SHELL
end
